# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ab827d1a3d6de602c4a1fefe15a832d562ad9c6201202e6593e1fe0312e58287ba46a1c44da389c3dc1ef726a183e9440b4ca034ad6c3a8de2fb631754aa35d

test:
  secret_key_base: a86a3fa217fe6dd431c422a24c025193e8aa1e5f9274712e605051ffe6171a1a86cb4b875b27d6b89921dad43385aaa4af765b99d2bcdbc526d134930bc423a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
